# i think for this problem we simply quantify the words, probably by each letter's position in the 
# english alphabet. then build a method that calculates amount of letter differences between 2 words.
# with that method, we can build a graph where each neighbor to a node is 1 letter away, 
# then use BFS to find the shortest path from one word to another.
# we can add short circuits in there to return early if for example we dont find endWord in wordList.
# actually i think that's an O(n^2) solution because we would have to loop through wordList twice to build the graph

# yeah that would be an O(n^2) solution at the least. rethinking this, we can build a data structure like below:
# {
#     "*at": ["cat", "bat"],
#     "c*t": ["cat"]
#     ...
# }
# and so forth by iterating over every word, then every char in that word. indexing by patterns generated by every letter
# we do this for every word then we have a fully populated dataset of patterns.

# then, we enque our beginWord and use BFS to look up patterns that we can use to find the shortest
# path to endWord. if no path is found, we simply return 0

# if a path is found, we return the amount of hops we made which we can store in the enqueue'd tuple

# one more important thing i didnt consider until now is we need to keep a seen hashset
# so we dont explore the same words over in a loop
class Solution:
    def ladderLength(self, beginWord: str, endWord: str, wordList: List[str]) -> int:
        # early return, per spec
        if endWord not in wordList:
            return 0

        graph = {}

        # building the pattern graph
        for word in wordList:
            # for every letter, we create a new pattern and index the current word
            for i in range(len(word)):
                # create the pattern
                # e.g. cat -> *at | c*t | ca*
                p = word[:i] + "*" + word[i+1:]

                # create new pattern index if one doesnt exist
                if p not in graph:
                    graph[p] = []

                # adding current word, indexed by current pattern
                graph[p].append(word)

        # enqueing the startWord
        # the tuple will contain 
        # (word, hops_so_far)
        q = deque([(beginWord, 0)])

        seen = set()

        # bfs over graph, from startWord, attempting to find endWord
        # for every word thats not endWord, we extract all patterns, look
        # them up in the graph, and move to elements in that list if the word isnt itself
        while len(q) > 0:
            word, hops = q.popleft()
            seen.add(word)

            # we've found endWord
            if word == endWord:
                return hops + 1

            for i in range(len(word)):
                p = word[:i] + "*" + word[i+1:]

                # start word wont always have a pattern
                # in the graph, so we can skip
                if p not in graph:
                    continue 

                neighbors = graph[p] 

                for n in neighbors:
                    if n in seen:
                        continue

                    # enque neighbor, increase hop
                    q.append((n, hops + 1))

        # endWord cannot be reached
        return 0

        